name: github pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages:     write
  id-token:  write

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: false

      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1

      - name: Copy CNAME
        run: cp CNAME _site/

      # ← Use the Pages artifact uploader, *not* the generic v3
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: _site

      - name: Deploy to Pages
        uses: actions/deploy-pages@v1
